export const FOOD_101_LABELS: string[] = [
  "apple_pie",
  "baby_back_ribs",
  "baklava",
  "beef_carpaccio",
  "beef_tartare",
  "beet_salad",
  "beignets",
  "bibimbap",
  "bread_pudding",
  "breakfast_burrito",
  "bruschetta",
  "caesar_salad",
  "cannoli",
  "caprese_salad",
  "carrot_cake",
  "ceviche",
  "cheese_plate",
  "cheesecake",
  "chicken_curry",
  "chicken_quesadilla",
  "chicken_wings",
  "chocolate_cake",
  "chocolate_mousse",
  "churros",
  "clam_chowder",
  "club_sandwich",
  "crab_cakes",
  "creme_brulee",
  "croque_madame",
  "cup_cakes",
  "deviled_eggs",
  "donuts",
  "dumplings",
  "edamame",
  "eggs_benedict",
  "escargots",
  "falafel",
  "filet_mignon",
  "fish_and_chips",
  "foie_gras",
  "french_fries",
  "french_onion_soup",
  "french_toast",
  "fried_calamari",
  "fried_rice",
  "frozen_yogurt",
  "garlic_bread",
  "gnocchi",
  "greek_salad",
  "grilled_cheese_sandwich",
  "grilled_salmon",
  "guacamole",
  "gyoza",
  "hamburger",
  "hot_and_sour_soup",
  "hot_dog",
  "huevos_rancheros",
  "hummus",
  "ice_cream",
  "lasagna",
  "lobster_bisque",
  "lobster_roll_sandwich",
  "macaroni_and_cheese",
  "macarons",
  "miso_soup",
  "mussels",
  "nachos",
  "omelette",
  "onion_rings",
  "oysters",
  "pad_thai",
  "paella",
  "pancakes",
  "panna_cotta",
  "peking_duck",
  "pho",
  "pizza",
  "pork_chop",
  "poutine",
  "prime_rib",
  "pulled_pork_sandwich",
  "ramen",
  "ravioli",
  "red_velvet_cake",
  "risotto",
  "samosa",
  "sashimi",
  "scallops",
  "seaweed_salad",
  "shrimp_and_grits",
  "spaghetti_bolognese",
  "spaghetti_carbonara",
  "spring_rolls",
  "steak",
  "strawberry_shortcake",
  "sushi",
  "tacos",
  "takoyaki",
  "tiramisu",
  "tuna_tartare",
  "waffles",
];

export const labelToQuery: Record<string, string> = {
  apple_pie: "apple pie",
  baby_back_ribs: "baby back ribs",
  baklava: "baklava",
  beef_carpaccio: "beef carpaccio",
  beef_tartare: "beef tartare",
  beet_salad: "beet salad",
  beignets: "beignets",
  bibimbap: "bibimbap",
  bread_pudding: "bread pudding",
  breakfast_burrito: "breakfast burrito",
  bruschetta: "bruschetta",
  caesar_salad: "caesar salad",
  cannoli: "cannoli",
  caprese_salad: "caprese salad",
  carrot_cake: "carrot cake",
  ceviche: "ceviche",
  cheese_plate: "cheese plate",
  cheesecake: "cheesecake",
  chicken_curry: "chicken curry",
  chicken_quesadilla: "chicken quesadilla",
  chicken_wings: "chicken wings",
  chocolate_cake: "chocolate cake",
  chocolate_mousse: "chocolate mousse",
  churros: "churros",
  clam_chowder: "clam chowder",
  club_sandwich: "club sandwich",
  crab_cakes: "crab cakes",
  creme_brulee: "creme brulee",
  croque_madame: "croque madame",
  cup_cakes: "cupcakes",
  deviled_eggs: "deviled eggs",
  donuts: "donuts",
  dumplings: "dumplings",
  edamame: "edamame",
  eggs_benedict: "eggs benedict",
  escargots: "escargots",
  falafel: "falafel",
  filet_mignon: "filet mignon",
  fish_and_chips: "fish and chips",
  foie_gras: "foie gras",
  french_fries: "french fries",
  french_onion_soup: "french onion soup",
  french_toast: "french toast",
  fried_calamari: "fried calamari",
  fried_rice: "fried rice",
  frozen_yogurt: "frozen yogurt",
  garlic_bread: "garlic bread",
  gnocchi: "gnocchi",
  greek_salad: "greek salad",
  grilled_cheese_sandwich: "grilled cheese sandwich",
  grilled_salmon: "grilled salmon",
  guacamole: "guacamole",
  gyoza: "gyoza",
  hamburger: "hamburger",
  hot_and_sour_soup: "hot and sour soup",
  hot_dog: "hot dog",
  huevos_rancheros: "huevos rancheros",
  hummus: "hummus",
  ice_cream: "ice cream",
  lasagna: "lasagna",
  lobster_bisque: "lobster bisque",
  lobster_roll_sandwich: "lobster roll sandwich",
  macaroni_and_cheese: "macaroni and cheese",
  macarons: "macarons",
  miso_soup: "miso soup",
  mussels: "mussels",
  nachos: "nachos",
  omelette: "omelette",
  onion_rings: "onion rings",
  oysters: "oysters",
  pad_thai: "pad thai",
  paella: "paella",
  pancakes: "pancakes",
  panna_cotta: "panna cotta",
  peking_duck: "peking duck",
  pho: "pho",
  pizza: "pizza",
  pork_chop: "pork chop",
  poutine: "poutine",
  prime_rib: "prime rib",
  pulled_pork_sandwich: "pulled pork sandwich",
  ramen: "ramen",
  ravioli: "ravioli",
  red_velvet_cake: "red velvet cake",
  risotto: "risotto",
  samosa: "samosa",
  sashimi: "sashimi",
  scallops: "scallops",
  seaweed_salad: "seaweed salad",
  shrimp_and_grits: "shrimp and grits",
  spaghetti_bolognese: "spaghetti bolognese",
  spaghetti_carbonara: "spaghetti carbonara",
  spring_rolls: "spring rolls",
  steak: "steak",
  strawberry_shortcake: "strawberry shortcake",
  sushi: "sushi",
  tacos: "tacos",
  takoyaki: "takoyaki",
  tiramisu: "tiramisu",
  tuna_tartare: "tuna tartare",
  waffles: "waffles",
};

export function getLabelQuery(label: string): string {
  return labelToQuery[label] ?? label.replace(/_/g, " ");
}
